// GENERADO por mobile/scripts/build-migrations.js a partir de /db/migrations/*.sql.
// No editar a mano: corre `npm run build:migrations` tras cambiar una migración.
module.exports = [
  {
    "name": "001_init.sql",
    "sql": "-- Esquema inicial. Ver docs/DESIGN.md para el razonamiento detrás de cada tabla.\n\nCREATE TABLE games (\n  id           INTEGER PRIMARY KEY,\n  source       TEXT NOT NULL CHECK (source IN ('steam', 'manual')),\n  steam_appid  INTEGER UNIQUE,\n  title        TEXT NOT NULL,\n  platform     TEXT NOT NULL,\n  icon_url     TEXT,\n  created_at   TEXT NOT NULL,\n  missing_since TEXT,\n  archived     INTEGER NOT NULL DEFAULT 0 CHECK (archived IN (0, 1)),\n  CHECK ((source = 'steam' AND steam_appid IS NOT NULL) OR (source = 'manual' AND steam_appid IS NULL))\n);\n\nCREATE TABLE steam_snapshots (\n  id                        INTEGER PRIMARY KEY,\n  game_id                   INTEGER NOT NULL REFERENCES games(id),\n  captured_at               TEXT NOT NULL,\n  playtime_forever_minutes  INTEGER NOT NULL,\n  playtime_2weeks_minutes   INTEGER,\n  UNIQUE (game_id, captured_at)\n);\n\nCREATE INDEX idx_steam_snapshots_game ON steam_snapshots(game_id);\n\nCREATE TABLE play_sessions (\n  id                  INTEGER PRIMARY KEY,\n  game_id             INTEGER NOT NULL REFERENCES games(id),\n  minutes             INTEGER NOT NULL CHECK (minutes >= 0),\n  started_at          TEXT,\n  ended_at            TEXT,\n  precision           TEXT NOT NULL CHECK (precision IN ('exact', 'approximate', 'derived')),\n  origin              TEXT NOT NULL CHECK (origin IN ('steam_sync', 'manual')),\n  source_snapshot_id  INTEGER REFERENCES steam_snapshots(id),\n  note                TEXT,\n  created_at          TEXT NOT NULL\n);\n\nCREATE INDEX idx_play_sessions_game ON play_sessions(game_id);\n\nCREATE TABLE sync_anomalies (\n  id           INTEGER PRIMARY KEY,\n  game_id      INTEGER NOT NULL REFERENCES games(id),\n  kind         TEXT NOT NULL CHECK (kind IN ('playtime_decreased', 'game_missing', 'game_reappeared')),\n  detail       TEXT,\n  occurred_at  TEXT NOT NULL\n);\n\nCREATE INDEX idx_sync_anomalies_game ON sync_anomalies(game_id);\n\nCREATE TABLE sync_runs (\n  id             INTEGER PRIMARY KEY,\n  started_at     TEXT NOT NULL,\n  finished_at    TEXT,\n  status         TEXT NOT NULL CHECK (status IN ('running', 'ok', 'error')),\n  games_synced   INTEGER,\n  error_message  TEXT\n);\n"
  },
  {
    "name": "002_achievements.sql",
    "sql": "-- Logros de Steam. A diferencia de las horas jugadas, Steam sí da una\n-- fecha exacta de desbloqueo por logro, así que no hace falta derivar\n-- nada de un par de instantáneas: cada sync simplemente actualiza el\n-- estado actual de cada logro.\n\nCREATE TABLE achievements (\n  id              INTEGER PRIMARY KEY,\n  game_id         INTEGER NOT NULL REFERENCES games(id),\n  api_name        TEXT NOT NULL,\n  name            TEXT,\n  description     TEXT,\n  achieved        INTEGER NOT NULL DEFAULT 0 CHECK (achieved IN (0, 1)),\n  unlocked_at     TEXT,\n  last_synced_at  TEXT NOT NULL,\n  UNIQUE (game_id, api_name)\n);\n\nCREATE INDEX idx_achievements_game ON achievements(game_id);\n"
  },
  {
    "name": "003_hltb.sql",
    "sql": "-- Tiempos de HowLongToBeat por juego. Es un dato 1:1 con el juego (no un\n-- histórico como steam_snapshots), así que vive como columnas de `games`\n-- en vez de una tabla propia. hltb_id permite volver a pedir el mismo\n-- juego a HowLongToBeat sin repetir la búsqueda por título.\n\nALTER TABLE games ADD COLUMN hltb_id INTEGER;\nALTER TABLE games ADD COLUMN hltb_main_minutes INTEGER;\nALTER TABLE games ADD COLUMN hltb_completionist_minutes INTEGER;\nALTER TABLE games ADD COLUMN hltb_updated_at TEXT;\n"
  },
  {
    "name": "004_igdb.sql",
    "sql": "-- 003_hltb.sql asumía que se podía hablar directamente con la búsqueda de\n-- howlongtobeat.com. Resultó que esa API no es viable: tiene una barrera\n-- anti-bot (token + honeypot) delante. La alternativa es IGDB (api.igdb.com,\n-- de Twitch), que expone el mismo dato (\"Game Time To Beat\") en una API\n-- oficial, documentada y sin protección anti-scraping. Se renombran las\n-- columnas para reflejar la fuente real de los datos.\n\nALTER TABLE games RENAME COLUMN hltb_id TO igdb_id;\nALTER TABLE games RENAME COLUMN hltb_main_minutes TO igdb_main_minutes;\nALTER TABLE games RENAME COLUMN hltb_completionist_minutes TO igdb_completionist_minutes;\nALTER TABLE games RENAME COLUMN hltb_updated_at TO igdb_updated_at;\n"
  },
  {
    "name": "005_multi_source.sql",
    "sql": "-- Preparar el modelo para más plataformas que Steam (Epic, GOG, Xbox...).\n--\n-- Dos cambios:\n--   1. El id externo de un juego deja de ser la columna `games.steam_appid`\n--      y pasa a una tabla aparte `game_external_ids (source, external_id)`,\n--      para no ir añadiendo una columna `*_appid` por cada tienda.\n--   2. `steam_snapshots` se renombra a `playtime_snapshots` y gana una\n--      columna `source`: el contador acumulado de horas es el mismo\n--      concepto venga de donde venga.\n--\n-- SQLite no deja quitar una columna con UNIQUE ni con una CHECK que la\n-- menciona, así que `games` se reconstruye entera. El runner de\n-- migraciones desactiva las FK mientras corre esto (ver db/migrate.js).\n\nCREATE TABLE game_external_ids (\n  game_id      INTEGER NOT NULL REFERENCES games(id),\n  source       TEXT NOT NULL CHECK (source IN ('steam', 'epic', 'gog', 'xbox')),\n  external_id  TEXT NOT NULL,\n  PRIMARY KEY (game_id, source),\n  UNIQUE (source, external_id)\n);\n\nINSERT INTO game_external_ids (game_id, source, external_id)\n  SELECT id, 'steam', CAST(steam_appid AS TEXT)\n  FROM games\n  WHERE steam_appid IS NOT NULL;\n\nCREATE TABLE games_new (\n  id                          INTEGER PRIMARY KEY,\n  source                      TEXT NOT NULL CHECK (source IN ('steam', 'manual', 'epic', 'gog', 'xbox')),\n  title                       TEXT NOT NULL,\n  platform                    TEXT NOT NULL,\n  icon_url                    TEXT,\n  created_at                  TEXT NOT NULL,\n  missing_since               TEXT,\n  archived                    INTEGER NOT NULL DEFAULT 0 CHECK (archived IN (0, 1)),\n  igdb_id                     INTEGER,\n  igdb_main_minutes           INTEGER,\n  igdb_completionist_minutes  INTEGER,\n  igdb_updated_at             TEXT\n);\n\nINSERT INTO games_new (\n  id, source, title, platform, icon_url, created_at, missing_since, archived,\n  igdb_id, igdb_main_minutes, igdb_completionist_minutes, igdb_updated_at\n)\n  SELECT\n    id, source, title, platform, icon_url, created_at, missing_since, archived,\n    igdb_id, igdb_main_minutes, igdb_completionist_minutes, igdb_updated_at\n  FROM games;\n\nDROP TABLE games;\nALTER TABLE games_new RENAME TO games;\n\n-- RENAME reconecta sola la FK de play_sessions.source_snapshot_id.\nALTER TABLE steam_snapshots RENAME TO playtime_snapshots;\nALTER TABLE playtime_snapshots ADD COLUMN source TEXT NOT NULL DEFAULT 'steam';\n\n-- Búsquedas por (source, external_id) las cubre el UNIQUE de arriba.\nDROP INDEX IF EXISTS idx_steam_snapshots_game;\nCREATE INDEX IF NOT EXISTS idx_playtime_snapshots_game ON playtime_snapshots(game_id);\n"
  },
  {
    "name": "006_xbox_origin.sql",
    "sql": "-- Permitir sesiones derivadas de la sync de Xbox. SQLite no deja modificar\n-- una CHECK, así que se reconstruye play_sessions (el runner de migraciones\n-- corre esto con las FK desactivadas).\n\nCREATE TABLE play_sessions_new (\n  id                  INTEGER PRIMARY KEY,\n  game_id             INTEGER NOT NULL REFERENCES games(id),\n  minutes             INTEGER NOT NULL CHECK (minutes >= 0),\n  started_at          TEXT,\n  ended_at            TEXT,\n  precision           TEXT NOT NULL CHECK (precision IN ('exact', 'approximate', 'derived')),\n  origin              TEXT NOT NULL CHECK (origin IN ('steam_sync', 'xbox_sync', 'manual')),\n  source_snapshot_id  INTEGER REFERENCES playtime_snapshots(id),\n  note                TEXT,\n  created_at          TEXT NOT NULL\n);\n\nINSERT INTO play_sessions_new\n  (id, game_id, minutes, started_at, ended_at, precision, origin, source_snapshot_id, note, created_at)\n  SELECT id, game_id, minutes, started_at, ended_at, precision, origin, source_snapshot_id, note, created_at\n  FROM play_sessions;\n\nDROP TABLE play_sessions;\nALTER TABLE play_sessions_new RENAME TO play_sessions;\n\nCREATE INDEX IF NOT EXISTS idx_play_sessions_game ON play_sessions(game_id);\n"
  },
  {
    "name": "007_epic_origin.sql",
    "sql": "-- Permitir sesiones derivadas de la sync de Epic. Igual que la 006 con\n-- Xbox: SQLite no deja modificar una CHECK, así que se reconstruye\n-- play_sessions (el runner de migraciones lo corre con las FK off).\n\nCREATE TABLE play_sessions_new (\n  id                  INTEGER PRIMARY KEY,\n  game_id             INTEGER NOT NULL REFERENCES games(id),\n  minutes             INTEGER NOT NULL CHECK (minutes >= 0),\n  started_at          TEXT,\n  ended_at            TEXT,\n  precision           TEXT NOT NULL CHECK (precision IN ('exact', 'approximate', 'derived')),\n  origin              TEXT NOT NULL CHECK (origin IN ('steam_sync', 'xbox_sync', 'epic_sync', 'manual')),\n  source_snapshot_id  INTEGER REFERENCES playtime_snapshots(id),\n  note                TEXT,\n  created_at          TEXT NOT NULL\n);\n\nINSERT INTO play_sessions_new\n  (id, game_id, minutes, started_at, ended_at, precision, origin, source_snapshot_id, note, created_at)\n  SELECT id, game_id, minutes, started_at, ended_at, precision, origin, source_snapshot_id, note, created_at\n  FROM play_sessions;\n\nDROP TABLE play_sessions;\nALTER TABLE play_sessions_new RENAME TO play_sessions;\n\nCREATE INDEX IF NOT EXISTS idx_play_sessions_game ON play_sessions(game_id);\n"
  },
  {
    "name": "008_game_covers.sql",
    "sql": "-- Carátula propia del usuario para un juego: una imagen que sube a mano\n-- (o pega por URL y el servidor descarga una vez). Tiene prioridad sobre\n-- el arte de Steam/Xbox y sobre icon_url; al borrarla, el juego vuelve a\n-- mostrar su carátula por defecto.\n--\n-- Vive en una tabla aparte para no arrastrar el BLOB en cada `SELECT g.*`\n-- de la lista: el hot path solo mira `updated_at` con una subquery.\n\nCREATE TABLE game_covers (\n  game_id     INTEGER PRIMARY KEY REFERENCES games(id),\n  mime        TEXT NOT NULL,\n  bytes       BLOB NOT NULL,\n  updated_at  TEXT NOT NULL\n);\n"
  },
  {
    "name": "009_to_play_list.sql",
    "sql": "-- \"Lista de siguientes\": los juegos que el usuario aparta para jugar\n-- próximamente, arrastrándolos a la zona de la izquierda. Una fila por\n-- juego (el id de la fila principal, tal como aparece en la lista\n-- agrupada). Se ordena por cuándo se añadió.\n\nCREATE TABLE to_play_list (\n  game_id   INTEGER PRIMARY KEY REFERENCES games(id),\n  added_at  TEXT NOT NULL\n);\n"
  },
  {
    "name": "010_gog_origin.sql",
    "sql": "-- Permitir sesiones derivadas de la sync de GOG. Igual que la 006 (Xbox) y\n-- la 007 (Epic): SQLite no deja modificar una CHECK, así que se reconstruye\n-- play_sessions (el runner de migraciones lo corre con las FK off).\n\nCREATE TABLE play_sessions_new (\n  id                  INTEGER PRIMARY KEY,\n  game_id             INTEGER NOT NULL REFERENCES games(id),\n  minutes             INTEGER NOT NULL CHECK (minutes >= 0),\n  started_at          TEXT,\n  ended_at            TEXT,\n  precision           TEXT NOT NULL CHECK (precision IN ('exact', 'approximate', 'derived')),\n  origin              TEXT NOT NULL CHECK (origin IN ('steam_sync', 'xbox_sync', 'epic_sync', 'gog_sync', 'manual')),\n  source_snapshot_id  INTEGER REFERENCES playtime_snapshots(id),\n  note                TEXT,\n  created_at          TEXT NOT NULL\n);\n\nINSERT INTO play_sessions_new\n  (id, game_id, minutes, started_at, ended_at, precision, origin, source_snapshot_id, note, created_at)\n  SELECT id, game_id, minutes, started_at, ended_at, precision, origin, source_snapshot_id, note, created_at\n  FROM play_sessions;\n\nDROP TABLE play_sessions;\nALTER TABLE play_sessions_new RENAME TO play_sessions;\n\nCREATE INDEX IF NOT EXISTS idx_play_sessions_game ON play_sessions(game_id);\n"
  },
  {
    "name": "011_cover_framing.sql",
    "sql": "-- Encuadre de la carátula por juego. El arte llega en proporciones distintas\n-- (Steam 2:3, Xbox casi cuadrado, header apaisado, subidas variadas) y la caja\n-- es 3:4, así que `object-fit: cover` siempre recorta por algún lado. Estos dos\n-- porcentajes son el `object-position` (X, Y) que el usuario ajusta a mano para\n-- decidir qué franja de la imagen se ve. 50/50 = centrado, el comportamiento\n-- por defecto.\n\nALTER TABLE games ADD COLUMN cover_pos_x INTEGER NOT NULL DEFAULT 50;\nALTER TABLE games ADD COLUMN cover_pos_y INTEGER NOT NULL DEFAULT 50;\n"
  },
  {
    "name": "012_settings.sql",
    "sql": "-- Configuración clave-valor. Pensada para el móvil, que no tiene .env:\n-- ahí guarda STEAM_API_KEY y STEAM_ID introducidos a mano en la app. El\n-- escritorio sigue usando variables de entorno; esta tabla queda sin usar\n-- ahí, pero es la misma base de datos y el mismo módulo db/settings.js.\nCREATE TABLE settings (\n  key    TEXT PRIMARY KEY,\n  value  TEXT NOT NULL\n);\n"
  }
];
